# Generated by Django 5.0.1 on 2024-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_usermodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='uid',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
