# Generated by Django 5.0.1 on 2024-01-20 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_expected_completion_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expected_completion_time',
        ),
    ]
