# Generated by Django 5.0.1 on 2024-01-21 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_expected_completion_time'),
        ('userauth', '0003_usermodel_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.usermodel'),
        ),
    ]
