# Generated by Django 5.0.1 on 2024-01-21 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_user'),
        ('userauth', '0004_alter_usermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.usermodel', to_field='uid'),
        ),
    ]
