# Generated by Django 5.0.1 on 2024-01-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
