# Generated by Django 5.0.1 on 2024-01-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
        ('userauth', '0004_alter_usermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='rooms', to='userauth.usermodel'),
        ),
    ]
