# Generated by Django 5.0.1 on 2024-01-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0002_room_users'),
        ('userauth', '0005_remove_usermodel_id_alter_usermodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.usermodel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='userauth.usermodel'),
        ),
    ]
