# Generated by Django 5.0.1 on 2024-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0004_remove_room_users'),
        ('userauth', '0005_remove_usermodel_id_alter_usermodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(to='userauth.usermodel'),
        ),
    ]
